import type { AgentSuggestion } from "@/types";

export const NON_MVP_AGENT_SUGGESTIONS: AgentSuggestion[] = [
  { id: "hackernews", name: "HackerNews Agent", phase: "phase2", tagline: "HN launch and comment playbook", signalFixed: ["Entity Association", "Use Case"], estimatedImpact: "high", whyNotMVP: "No write API; copy-paste UX polish deferred", prerequisite: "Community baseline content", cta: "coming_soon" },
  { id: "social", name: "Social Media Agent (LinkedIn/X)", phase: "phase2", tagline: "OAuth-connected posting assistance", signalFixed: ["Category Clarity"], estimatedImpact: "high", whyNotMVP: "Requires OAuth integrations", prerequisite: "Canonical definition complete", cta: "request_early_access" },
  { id: "faq_schema", name: "FAQ & Schema Agent", phase: "phase2", tagline: "CMS-aware FAQ and schema automation", signalFixed: ["Authoritative Definition"], estimatedImpact: "high", whyNotMVP: "CMS integration research", prerequisite: "Technical audit clean", cta: "coming_soon" },
  { id: "founder_content", name: "Founder Content Agent", phase: "phase2", tagline: "Tone-calibrated founder posts", signalFixed: ["Entity Association"], estimatedImpact: "medium", whyNotMVP: "Tone calibration per founder", prerequisite: "Brand consistency audit", cta: "request_early_access" },
  { id: "usecase_lp", name: "Use Case Landing Page Agent", phase: "phase2", tagline: "Dedicated pages per use case", signalFixed: ["Use Case Saturation"], estimatedImpact: "high", whyNotMVP: "Long output needs editor UI", prerequisite: "Semantic keyword map", cta: "coming_soon" },
  { id: "case_study", name: "Case Study & Outcome Language Agent", phase: "phase2", tagline: "Outcome narratives from customer stories", signalFixed: ["Comparison"], estimatedImpact: "high", whyNotMVP: "Customer interview workflow", prerequisite: "Semantic clusters defined", cta: "coming_soon" },
  { id: "directory", name: "Directory & Listing Agent", phase: "phase2", tagline: "Multi-directory listing consistency", signalFixed: ["Entity Association"], estimatedImpact: "medium", whyNotMVP: "Platform copy variance", prerequisite: "Canonical definitions", cta: "coming_soon" },
  { id: "integration", name: "Integration & Ecosystem Content Agent", phase: "phase2", tagline: "Integration hub and comparison pages", signalFixed: ["Comparison"], estimatedImpact: "medium", whyNotMVP: "Integration research overhead", prerequisite: "Technical SEO baseline", cta: "coming_soon" },
  { id: "recency", name: "Recency Spike Agent", phase: "phase2", tagline: "Calendar-driven topical spikes", signalFixed: ["Category Clarity"], estimatedImpact: "medium", whyNotMVP: "Scheduling UI", prerequisite: "Content calendar", cta: "coming_soon" },
  { id: "press", name: "Press & Link Agent", phase: "phase3", tagline: "Journalist outreach and digital PR", signalFixed: ["Authoritative Definition"], estimatedImpact: "high", whyNotMVP: "Journalist database required", prerequisite: "Newsworthy milestones", cta: "request_early_access" },
  { id: "bing", name: "Bing Optimization Agent", phase: "phase3", tagline: "Bing Webmaster and citation tuning", signalFixed: ["Real-time search"], estimatedImpact: "high", whyNotMVP: "Bing API + tooling", prerequisite: "Technical crawl passing", cta: "coming_soon" },
  { id: "kg", name: "Knowledge Graph Entity Agent", phase: "phase3", tagline: "Wikidata / KG entity strategy", signalFixed: ["Entity Association"], estimatedImpact: "high", whyNotMVP: "Wikipedia complexity", prerequisite: "Notability assets", cta: "coming_soon" },
  { id: "perplexity_cite", name: "Perplexity Citation Agent", phase: "phase3", tagline: "Citation-oriented content packaging", signalFixed: ["Authoritative Definition"], estimatedImpact: "medium", whyNotMVP: "Platform evolving", prerequisite: "Strong owned pages", cta: "coming_soon" },
];
